"""Actualizar customer_id nullable y agregar departamentos

Revision ID: bbf45e6fa095
Revises: 
Create Date: 2026-01-23 21:39:52.929648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbf45e6fa095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('warehouse_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purchasing_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('production_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('logistics_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_service_notes', sa.Text(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('promised_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('promised_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('customer_service_notes')
        batch_op.drop_column('logistics_status')
        batch_op.drop_column('production_status')
        batch_op.drop_column('purchasing_status')
        batch_op.drop_column('warehouse_status')
        batch_op.drop_column('planning_status')

    # ### end Alembic commands ###
